### ISSUE TITLE
OBS Message not connecting via OBS Web Socket

### ISSUE THREAD

**Issue by designbymichael** [mrgoodbytes8667/obsmessage#9] opened 2022-10-04 20:37 UTC
OBS version 28.0.3
Elgato Stream Deck version 5.3.3

No additional information available to me.  I've entered the correct IP address, port, and password and it continually fails to connect.  I've verified the web socket settings in OBS and they match what I've entered in Stream Deck.

**Comment by mrgoodbytes8667** [comment] 2022-10-05 02:22
Duplicate of #8

**Closed as completed by mrgoodbytes8667** 2022-10-05 02:22 UTC
